// ┌──────────────────────────────────────────────────────────┐
// │  MORPHIC SYNTHESIS ENGINE                                │
// │                                                          │
// │  Architecture:                                            │
// │  ┌─────────┐   ┌──────────┐   ┌──────────┐   ┌────────┐ │
// │  │  Spec   │──▶│   MCTS   │──▶│   Gen    │──▶│ Verify │ │
// │  │  Tree   │   │  Search  │   │ Candidate│   │  (Z3)  │ │
// │  └─────────┘   └──────────┘   └──────────┘   └────────┘ │
// │                      │                ▲            │     │
// │                      └─────── reward ─┘            │     │
// │                                 ┌────────────┐     │     │
// │                                 │  LLM Hint  │◀────┘     │
// │                                 └────────────┘           │
// └──────────────────────────────────────────────────────────┘

use std::sync::Mutex;
use std::sync::atomic::{AtomicU64, Ordering};
use crate::spec::ast::*;
use rand::Rng;

// ── Global synthesis statistics ──────────────────────────

static CANDIDATE_COUNT: AtomicU64 = AtomicU64::new(0);
static ELAPSED_MS: AtomicU64 = AtomicU64::new(0);

pub fn candidate_count() -> u64 { CANDIDATE_COUNT.load(Ordering::Relaxed) }
pub fn elapsed_ms() -> u64 { ELAPSED_MS.load(Ordering::Relaxed) }

// ── Candidate Representation ──────────────────────────────

/// A synthesized implementation candidate
///
/// Each candidate is an AST subtree representing a possible
/// implementation of the spec. Candidates live in a space
/// where mutations, crossovers, and refinements are valid
/// operations.
#[derive(Debug, Clone)]
pub struct CandidateImplementation {
    /// Unique identifier
    pub id: u64,

    /// The implementation body (in Intermediate Representation)
    pub body: IRNode,

    /// Source function this implements
    pub spec_name: String,

    /// The spec this implements
    pub spec: FunctionSpec,

    /// Quality score (0.0–1.0)
    pub score: f64,

    /// Scores broken down by dimension
    pub scores: ScoreBreakdown,

    /// Number of mutations from original seed
    pub generation: u64,

    /// How this candidate was created
    pub provenance: Provenance,

    /// Whether this candidate passed verification
    pub verified: bool,
}

#[derive(Debug, Clone)]
pub struct ScoreBreakdown {
    /// How many test cases passed
    pub test_pass_ratio: f64,
    /// How well it satisfies constraints (Z3 score)
    pub constraint_score: f64,
    /// Complexity efficiency vs spec bounds
    pub complexity_score: f64,
    /// Readability / code quality
    pub quality_score: f64,
    /// Synthesis runtime in microseconds
    pub synthesis_time_us: u64,
}

#[derive(Debug, Clone)]
pub enum Provenance {
    /// Generated by LLM from spec
    LLMGenerated { model: String, prompt_hash: u64 },
    /// Random mutation of parent
    Mutation { parent_id: u64, mutation_kind: String },
    /// Crossover between two parents
    Crossover { parent_a: u64, parent_b: u64 },
    /// Seeded from test cases (inductive synthesis)
    TestInduced { num_tests: usize },
    /// Built from predefined template
    Template { template_name: String },
    /// Human-provided partial implementation
    HumanGuided,
}

// ── Intermediate Representation (IR) ─────────────────────

/// The Morphic IR — an abstraction over concrete syntax.
///
/// The IR is designed to be:
/// - Language-agnostic (compile to Rust, C, WASM, etc.)
/// - Mutable (nodes can be rewritten during search)
/// - Verifiable (easily lowered to Z3 SMT-LIB)
/// - Lightweight (cheap to clone for GA/MCTS operations)
#[derive(Debug, Clone)]
pub enum IRNode {
    /// Empty / hole — to be filled by synthesis
    Hole { id: u64, expected_type: Option<TypeRef> },

    /// Sequence of statements
    Block(Vec<IRNode>),

    /// Variable binding: let x = value in body
    Let {
        name: String,
        value: Box<IRNode>,
        body: Box<IRNode>,
    },

    /// If-then-else
    If {
        condition: Box<IRNode>,
        then_branch: Box<IRNode>,
        else_branch: Box<IRNode>,
    },

    /// While loop
    While {
        condition: Box<IRNode>,
        body: Box<IRNode>,
        invariant: Option<String>, // Z3 loop invariant
    },

    /// For loop with known bound
    For {
        var: String,
        start: Box<IRNode>,
        end: Box<IRNode>,
        body: Box<IRNode>,
    },

    /// Pattern match
    Match {
        scrutinee: Box<IRNode>,
        cases: Vec<(IRPattern, IRNode)>,
    },

    /// Function call
    Call {
        function: String,
        args: Vec<IRNode>,
    },

    /// Return statement
    Return(Box<IRNode>),

    /// Literal value
    Literal(IRLiteral),

    /// Variable reference
    Var(String),

    /// Binary operation
    BinOp(IRBinOp, Box<IRNode>, Box<IRNode>),

    /// Unary operation
    UnaryOp(IRUnaryOp, Box<IRNode>),

    /// Lambda expression
    Lambda {
        params: Vec<(String, TypeRef)>,
        body: Box<IRNode>,
    },

    /// Closure (lambda with captured environment)
    Closure {
        params: Vec<(String, TypeRef)>,
        captures: Vec<String>,
        body: Box<IRNode>,
    },

    /// Collection literal
    Collection {
        kind: CollectionKind,
        elements: Vec<IRNode>,
    },

    /// Map / Higher-order function
    Map {
        function: Box<IRNode>,
        over: Box<IRNode>,
    },

    /// Filter
    Filter {
        predicate: Box<IRNode>,
        over: Box<IRNode>,
    },

    /// Fold / Reduce
    Fold {
        operation: Box<IRNode>,
        initial: Box<IRNode>,
        over: Box<IRNode>,
    },

    /// Sort by comparator
    Sort {
        comparator: Box<IRNode>,
        collection: Box<IRNode>,
    },

    /// Allocate mutable state
    Alloc {
        name: String,
        ty: TypeRef,
        initial: Box<IRNode>,
    },

    /// Mutation
    Assign {
        target: Box<IRNode>,
        value: Box<IRNode>,
    },

    /// Raw expression with type annotation
    Typed {
        node: Box<IRNode>,
        ty: TypeRef,
    },
}

#[derive(Debug, Clone)]
pub enum IRLiteral {
    Int(i64),
    Float(f64),
    Bool(bool),
    String(String),
    Char(char),
    Unit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IRBinOp {
    Add, Sub, Mul, Div, Mod,
    And, Or, Xor,
    Eq, Neq, Lt, Le, Gt, Ge,
    Shl, Shr,
    Concat,
    Append,
    Merge,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IRUnaryOp {
    Neg, Not, Abs, Len,
    Head, Tail, Init, Last,
    Reverse,
    Clone,
}

#[derive(Debug, Clone)]
pub enum IRPattern {
    Wildcard,
    Variable(String),
    Literal(IRLiteral),
    Constructor(String, Vec<IRPattern>),
    Guard(Box<IRPattern>, String), // Pattern with guard condition
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CollectionKind {
    List,
    Set,
    Map,
    Array,
    Tuple,
}

// ── MCTS Node ─────────────────────────────────────────────

/// A node in the Monte Carlo Tree Search over implementation space
#[derive(Debug, Clone)]
struct MCTSNode {
    /// The IR state at this node
    state: IRNode,

    /// Parent node index (for backpropagation)
    parent: Option<usize>,

    /// Children indices
    children: Vec<usize>,

    /// Visit count for UCT
    visits: u64,

    /// Total accumulated reward
    total_reward: f64,

    /// Whether this is a terminal (complete implementation)
    is_terminal: bool,

    /// Number of holes remaining
    hole_count: usize,
}

impl MCTSNode {
    fn uct_value(&self, parent_visits: u64, exploration: f64) -> f64 {
        if self.visits == 0 {
            return f64::MAX; // Unvisited nodes get priority
        }
        let exploitation = self.total_reward / self.visits as f64;
        let exploration = exploration * ((parent_visits as f64).ln() / self.visits as f64).sqrt();
        exploitation + exploration
    }
}

// ── Synthesis Configuration ───────────────────────────────

#[derive(Debug, Clone)]
pub struct SynthesisConfig {
    /// Optimization level (1=correctness only, 4=aggressive optimization)
    pub opt_level: u8,

    /// Maximum MCTS iterations
    pub max_iterations: u64,

    /// Maximum wall-clock time (milliseconds)
    pub max_time_ms: u64,

    /// Exploration constant for UCT selection
    pub uct_exploration: f64,

    /// Population size for genetic phase
    pub population_size: usize,

    /// Tournament size for selection
    pub tournament_size: usize,

    /// Mutation rate (probability per node)
    pub mutation_rate: f64,

    /// Crossover rate
    pub crossover_rate: f64,

    /// Whether to use LLM for candidate generation
    pub use_llm: bool,

    /// Whether to use Z3 for verification
    pub use_z3: bool,

    /// Minimum score threshold for acceptance
    pub min_score: f64,
}

impl Default for SynthesisConfig {
    fn default() -> Self {
        Self {
            opt_level: 3,
            max_iterations: 10_000,
            max_time_ms: 30_000, // 30 seconds
            uct_exploration: 1.414,
            population_size: 100,
            tournament_size: 5,
            mutation_rate: 0.3,
            crossover_rate: 0.7,
            use_llm: true,
            use_z3: true,
            min_score: 0.0,
        }
    }
}

impl SynthesisConfig {
    pub fn from_opt_level(level: u8) -> Self {
        match level {
            1 => Self {
                opt_level: 1,
                max_iterations: 1_000,
                max_time_ms: 5_000,
                use_llm: false,
                use_z3: true,
                population_size: 20,
                ..Default::default()
            },
            2 => Self {
                opt_level: 2,
                max_iterations: 5_000,
                max_time_ms: 15_000,
                use_llm: true,
                use_z3: true,
                population_size: 50,
                ..Default::default()
            },
            3 => Self::default(),
            4 => Self {
                opt_level: 4,
                max_iterations: 100_000,
                max_time_ms: 60_000,
                use_llm: true,
                use_z3: true,
                population_size: 500,
                uct_exploration: 2.0,
                min_score: 0.9,
                ..Default::default()
            },
            _ => Self::default(),
        }
    }
}

// ── Synthesis Engine ──────────────────────────────────────

pub struct SynthesisEngine {
    config: SynthesisConfig,
    candidates: Vec<CandidateImplementation>,
    next_id: AtomicU64,
}

impl SynthesisEngine {
    pub fn new(config: SynthesisConfig) -> Self {
        Self {
            config,
            candidates: Vec::new(),
            next_id: AtomicU64::new(1),
        }
    }

    fn new_id(&self) -> u64 {
        self.next_id.fetch_add(1, Ordering::SeqCst)
    }

    pub fn run(&mut self, spec: &FunctionSpec) -> Result<Vec<CandidateImplementation>, SynthesisError> {
        let start = std::time::Instant::now();

        // Phase 1: Seed the population
        let mut population = self.seed_population(spec)?;

        // Phase 2: MCTS-guided exploration
        population = self.mcts_search(population, spec)?;

        // Phase 3: Genetic refinement
        if self.config.opt_level >= 3 {
            population = self.genetic_refine(population, spec)?;
        }

        // Phase 4: Scoring & ranking
        self.score_and_rank(&mut population, spec);

        // Phase 5: Filter passing candidates
        let passing: Vec<CandidateImplementation> = population
            .into_iter()
            .filter(|c| c.score >= self.config.min_score)
            .collect();

        // Update stats
        CANDIDATE_COUNT.store(self.candidates.len() as u64, Ordering::Relaxed);
        ELAPSED_MS.store(start.elapsed().as_millis() as u64, Ordering::Relaxed);

        Ok(passing)
    }

    // ── Phase 1: Seeding ──────────────────────────────────

    fn seed_population(&mut self, spec: &FunctionSpec) -> Result<Vec<CandidateImplementation>, SynthesisError> {
        let mut population = Vec::with_capacity(self.config.population_size);

        // Seed 1: From test cases (inductive synthesis)
        if !spec.tests.is_empty() {
            let test_induced = self.seed_from_tests(spec)?;
            population.extend(test_induced);
        }

        // Seed 2: From templates / pattern matching
        let template = self.seed_from_templates(spec)?;
        population.extend(template);

        // Seed 3: From LLM (if enabled)
        if self.config.use_llm {
            let llm_seeds = self.seed_from_llm(spec)?;
            population.extend(llm_seeds);
        }

        // Seed 4: Random AST generation (bootstrap diversity)
        while population.len() < self.config.population_size {
            let random = self.seed_random(spec);
            population.push(random);
        }

        // Deduplicate
        population.sort_by(|a, b| b.score.partial_cmp(&a.score).unwrap_or(std::cmp::Ordering::Equal));
        population.dedup_by(|a, b| ir_equivalent(&a.body, &b.body));
        population.truncate(self.config.population_size);

        self.candidates = population.clone();

        Ok(population)
    }

    fn seed_from_tests(&self, spec: &FunctionSpec) -> Result<Vec<CandidateImplementation>, SynthesisError> {
        if spec.tests.is_empty() {
            return Ok(Vec::new());
        }

        // Inductive synthesis: use test I/O pairs to derive implementation
        // Start with a match on test inputs → return test outputs
        let mut cases = Vec::new();
        for test in &spec.tests {
            let pattern = expr_to_pattern(&test.input);
            let output = expr_to_ir(&test.expected_output);
            cases.push((pattern, output));
        }

        // Wrap in a match with a default hole
        cases.push((IRPattern::Wildcard, IRNode::Hole {
            id: self.new_id(),
            expected_type: Some(spec.return_type.clone()),
        }));

        let body = IRNode::Match {
            scrutinee: Box::new(build_input_ref(&spec.params)),
            cases,
        };

        let candidate = CandidateImplementation {
            id: self.new_id(),
            body,
            spec_name: spec.name.clone(),
            spec: spec.clone(),
            score: 0.0,
            scores: empty_scores(),
            generation: 0,
            provenance: Provenance::TestInduced { num_tests: spec.tests.len() },
            verified: false,
        };

        Ok(vec![candidate])
    }

    fn seed_from_templates(&self, spec: &FunctionSpec) -> Result<Vec<CandidateImplementation>, SynthesisError> {
        let mut seeds = Vec::new();

        // Template: Recursive divide-and-conquer (for list types)
        if has_list_type(spec) {
            let dc_body = build_divide_and_conquer(spec, self);
            seeds.push(CandidateImplementation {
                id: self.new_id(),
                body: dc_body,
                spec_name: spec.name.clone(),
                spec: spec.clone(),
                score: 0.0,
                scores: empty_scores(),
                generation: 0,
                provenance: Provenance::Template { template_name: "divide_and_conquer".into() },
                verified: false,
            });
        }

        // Template: Iterator chain (map → filter → fold)
        let iter_body = build_iterator_chain(spec, self);
        seeds.push(CandidateImplementation {
            id: self.new_id(),
            body: iter_body,
            spec_name: spec.name.clone(),
            spec: spec.clone(),
            score: 0.0,
            scores: empty_scores(),
            generation: 0,
            provenance: Provenance::Template { template_name: "iterator_chain".into() },
            verified: false,
        });

        // Template: Simple loop (for the straightforward approach)
        let loop_body = build_simple_loop(spec, self);
        seeds.push(CandidateImplementation {
            id: self.new_id(),
            body: loop_body,
            spec_name: spec.name.clone(),
            spec: spec.clone(),
            score: 0.0,
            scores: empty_scores(),
            generation: 0,
            provenance: Provenance::Template { template_name: "simple_loop".into() },
            verified: false,
        });

        Ok(seeds)
    }

    fn seed_from_llm(&self, spec: &FunctionSpec) -> Result<Vec<CandidateImplementation>, SynthesisError> {
        // Generate prompt for LLM
        let prompt = self.build_llm_prompt(spec);

        // Call LLM (local via llama.cpp or remote via API)
        let llm_output = self.call_llm(&prompt)?;

        // Parse LLM output into IR nodes
        let candidates = self.parse_llm_output(&llm_output, spec)?;

        Ok(candidates)
    }

    fn seed_random(&self, spec: &FunctionSpec) -> CandidateImplementation {
        let body = random_ir_tree(spec, 3, self);
        CandidateImplementation {
            id: self.new_id(),
            body,
            spec_name: spec.name.clone(),
            spec: spec.clone(),
            score: 0.0,
            scores: empty_scores(),
            generation: 0,
            provenance: Provenance::Mutation { parent_id: 0, mutation_kind: "random_seed".into() },
            verified: false,
        }
    }

    // ── Phase 2: MCTS Search ──────────────────────────────

    fn mcts_search(
        &mut self,
        population: Vec<CandidateImplementation>,
        spec: &FunctionSpec,
    ) -> Result<Vec<CandidateImplementation>, SynthesisError> {
        let mut tree: Vec<MCTSNode> = Vec::new();
        let mut population = population;

        for _ in 0..self.config.max_iterations {
            // Selection
            let node_idx = self.mcts_select(&tree);
            if node_idx.is_none() {
                // Initialize from population member
                let parent = population[rand::thread_rng().gen_range(0..population.len())].clone();
                let node = MCTSNode {
                    state: parent.body.clone(),
                    parent: None,
                    children: Vec::new(),
                    visits: 0,
                    total_reward: 0.0,
                    is_terminal: count_holes(&parent.body) == 0,
                    hole_count: count_holes(&parent.body),
                };
                let idx = tree.len();
                tree.push(node);
                continue;
            }

            let idx = node_idx.unwrap();

            // Expansion
            if !tree[idx].is_terminal && tree[idx].children.is_empty() {
                let children = self.mcts_expand(&tree[idx], spec);
                let parent_idx = idx;
                for child_state in children {
                    let child_idx = tree.len();
                    let hole_count = count_holes(&child_state);
                    tree.push(MCTSNode {
                        state: child_state,
                        parent: Some(parent_idx),
                        children: Vec::new(),
                        visits: 0,
                        total_reward: 0.0,
                        is_terminal: hole_count == 0,
                        hole_count,
                    });
                    tree[parent_idx].children.push(child_idx);
                }
            }

            // Simulation: pick a child and simulate to completion
            let selected_child = if tree[idx].children.is_empty() {
                idx
            } else {
                let child_idx = rand::thread_rng().gen_range(0..tree[idx].children.len());
                tree[idx].children[child_idx]
            };

            // Rollout: fill remaining holes randomly
            let completed = self.mcts_rollout(&tree[selected_child].state, spec);
            let reward = self.mcts_evaluate(&completed, spec);

            // Backpropagation
            self.mcts_backpropagate(&mut tree, selected_child, reward);
        }

        // Harvest: extract best complete implementations from tree
        let mut harvested: Vec<CandidateImplementation> = Vec::new();
        for node in &tree {
            if node.is_terminal && node.visits > 0 {
                let score = node.total_reward / node.visits as f64;
                if score >= self.config.min_score {
                    harvested.push(CandidateImplementation {
                        id: self.new_id(),
                        body: node.state.clone(),
                        spec_name: spec.name.clone(),
                        spec: spec.clone(),
                        score,
                        scores: ScoreBreakdown {
                            test_pass_ratio: score,
                            constraint_score: score,
                            complexity_score: 1.0,
                            quality_score: 0.5,
                            synthesis_time_us: 0,
                        },
                        generation: 1,
                        provenance: Provenance::Mutation {
                            parent_id: 0,
                            mutation_kind: "mcts_harvest".into(),
                        },
                        verified: false,
                    });
                }
            }
        }

        population.extend(harvested);
        Ok(population)
    }

    fn mcts_select(&self, tree: &[MCTSNode]) -> Option<usize> {
        if tree.is_empty() { return None; }
        let total_visits: u64 = tree.iter().map(|n| n.visits).sum();
        let root = tree[0].clone();
        let mut current = 0usize;

        loop {
            if tree[current].is_terminal || tree[current].children.is_empty() {
                return Some(current);
            }

            let mut best_child = None;
            let mut best_uct = -1.0f64;

            for &child_idx in &tree[current].children {
                let uct = tree[child_idx].uct_value(total_visits, self.config.uct_exploration);
                if uct > best_uct {
                    best_uct = uct;
                    best_child = Some(child_idx);
                }
            }

            match best_child {
                Some(idx) => current = idx,
                None => return Some(current),
            }
        }
    }

    fn mcts_expand(&self, node: &MCTSNode, _spec: &FunctionSpec) -> Vec<IRNode> {
        let mut children = Vec::new();

        // Find first hole in the tree
        let holes = find_hole_positions(&node.state);
        if holes.is_empty() {
            return children;
        }

        // Generate multiple fillings for the first hole
        let hole = &holes[0];
        let fillings = generate_hole_fillings(hole, node);

        for filling in fillings {
            let mut new_state = node.state.clone();
            replace_hole(&mut new_state, hole, &filling);
            children.push(new_state);
        }

        children
    }

    fn mcts_rollout(&self, node: &IRNode, _spec: &FunctionSpec) -> IRNode {
        let mut current = node.clone();
        let max_iterations = 100; // Prevent infinite loops

        for _ in 0..max_iterations {
            let holes = find_hole_positions(&current);
            if holes.is_empty() { break; }

            let hole = &holes[0];
            // Random filling for rollout
            let filling = random_filling(hole);
            replace_hole(&mut current, hole, &filling);
        }

        current
    }

    fn mcts_evaluate(&self, node: &IRNode, spec: &FunctionSpec) -> f64 {
        let candidate = CandidateImplementation {
            id: 0,
            body: node.clone(),
            spec_name: spec.name.clone(),
            spec: spec.clone(),
            score: 0.0,
            scores: empty_scores(),
            generation: 0,
            provenance: Provenance::Template { template_name: "eval".into() },
            verified: false,
        };

        let scores = evaluate_candidate(&candidate, spec);
        // Weighted composite score
        0.4 * scores.test_pass_ratio
            + 0.3 * scores.constraint_score
            + 0.2 * scores.complexity_score
            + 0.1 * scores.quality_score
    }

    fn mcts_backpropagate(&self, tree: &mut Vec<MCTSNode>, leaf_idx: usize, reward: f64) {
        let mut current = leaf_idx;
        loop {
            tree[current].visits += 1;
            tree[current].total_reward += reward;
            if let Some(parent) = tree[current].parent {
                current = parent;
            } else {
                break;
            }
        }
    }

    // ── Phase 3: Genetic Refinement ───────────────────────

    fn genetic_refine(
        &mut self,
        population: Vec<CandidateImplementation>,
        _spec: &FunctionSpec,
    ) -> Result<Vec<CandidateImplementation>, SynthesisError> {
        let mut pop: Vec<CandidateImplementation> = population
            .into_iter()
            .map(|c| CandidateImplementation { id: self.new_id(), ..c })
            .collect();
        let mut rng = rand::thread_rng();

        for _gen in 0..10 { // Genetic generations
            // Evaluate all
            for c in &mut pop {
                c.scores = evaluate_candidate(c, &c.spec);
                c.score = composite_score(&c.scores);
            }

            // Sort by fitness
            pop.sort_by(|a, b| b.score.partial_cmp(&a.score).unwrap_or(std::cmp::Ordering::Equal));

            // Elitism: keep top 10%
            let elite_count = (pop.len() as f64 * 0.1) as usize;
            let mut new_pop: Vec<CandidateImplementation> = pop[..elite_count].to_vec();

            // Fill rest with crossover + mutation
            while new_pop.len() < pop.len() {
                let parent_a = tournament_select(&pop, self.config.tournament_size, &mut rng);
                let parent_b = tournament_select(&pop, self.config.tournament_size, &mut rng);

                let child = if rng.gen::<f64>() < self.config.crossover_rate {
                    self.crossover(parent_a, parent_b)
                } else if rng.gen::<f64>() < self.config.mutation_rate {
                    self.mutate(parent_a)
                } else {
                    parent_a.clone()
                };

                new_pop.push(CandidateImplementation {
                    id: self.new_id(),
                    generation: parent_a.generation.max(parent_b.generation) + 1,
                    ..child
                });
            }

            pop = new_pop;
        }

        Ok(pop)
    }

    fn crossover(&self, parent_a: &CandidateImplementation, parent_b: &CandidateImplementation) -> CandidateImplementation {
        // Semantic crossover: swap subtrees of same type
        let sub_a = random_subtree(&parent_a.body);
        let sub_b = random_subtree(&parent_b.body);

        let mut child_body = parent_a.body.clone();
        if type_compatible(&sub_a, &sub_b) {
            replace_subtree(&mut child_body, &sub_a, &sub_b);
        }

        CandidateImplementation {
            id: 0,
            body: child_body,
            spec_name: parent_a.spec_name.clone(),
            spec: parent_a.spec.clone(),
            score: 0.0,
            scores: empty_scores(),
            generation: 0,
            provenance: Provenance::Crossover {
                parent_a: parent_a.id,
                parent_b: parent_b.id,
            },
            verified: false,
        }
    }

    fn mutate(&self, parent: &CandidateImplementation) -> CandidateImplementation {
        use rand::Rng;
        let mut rng = rand::thread_rng();
        let mut body = parent.body.clone();

        let kind = match rng.gen_range(0u32..6) {
            0 => {
                // Replace a subtree with a hole (un-synthesize)
                let subtree = random_subtree(&body);
                let hole = IRNode::Hole { id: self.new_id(), expected_type: None };
                replace_subtree(&mut body, &subtree, &hole);
                "un_synthesize"
            }
            1 => {
                // Inline a function call
                inline_random_call(&mut body);
                "inline"
            }
            2 => {
                // Swap equivalent expressions
                swap_equivalent(&mut body);
                "swap_equivalent"
            }
            3 => {
                // Tighten loop / optimize
                optimize_loop(&mut body);
                "optimize_loop"
            }
            4 => {
                // Add parallelization hint
                add_parallel_hint(&mut body);
                "parallel"
            }
            _ => {
                // Random AST rewrite
                random_rewrite(&mut body);
                "rewrite"
            }
        };

        CandidateImplementation {
            id: 0,
            body,
            spec_name: parent.spec_name.clone(),
            spec: parent.spec.clone(),
            score: 0.0,
            scores: empty_scores(),
            generation: parent.generation + 1,
            provenance: Provenance::Mutation {
                parent_id: parent.id,
                mutation_kind: kind.into(),
            },
            verified: false,
        }
    }

    // ── Phase 4: Scoring ──────────────────────────────────

    fn score_and_rank(&self, population: &mut Vec<CandidateImplementation>, _spec: &FunctionSpec) {
        for c in population.iter_mut() {
            c.scores = evaluate_candidate(c, &c.spec);
            c.score = composite_score(&c.scores);
        }
        population.sort_by(|a, b| b.score.partial_cmp(&a.score).unwrap_or(std::cmp::Ordering::Equal));
    }

    // ── LLM Integration ───────────────────────────────────

    fn build_llm_prompt(&self, spec: &FunctionSpec) -> String {
        format!(
            r#"You are Morphic, a program synthesis engine.
Given a formal specification, generate Rust code that implements it.

SPECIFICATION for `{}`:
- Input parameters: {}
- Return type: {}
- Preconditions: {}
- Postconditions: {}
- Complexity requirement: {}
- Test cases: {}

Generate a COMPLETE, CORRECT Rust implementation.
The implementation MUST:
1. Satisfy all constraints
2. Meet the complexity bounds
3. Handle all edge cases
4. Be idiomatic and readable

Return ONLY the function body code (the function signature is auto-generated).
Write the code inside <code>...</code> tags."#,
            spec.name,
            format_params(&spec.params),
            spec.return_type,
            format_constraints(&spec.preconditions),
            format_constraints(&spec.postconditions),
            spec.complexity.as_ref().map(|c| format!("{} {}", c.dimension_name(), c.bound)).unwrap_or_else(|| "none".into()),
            format_tests(&spec.tests),
        )
    }

    fn call_llm(&self, prompt: &str) -> Result<String, SynthesisError> {
        // Try llama.cpp first (local), fall back to API
        #[cfg(feature = "llm-local")]
        {
            // Use llama-cpp-2 for local inference
            // let output = llama_cpp_2::generate(prompt, 512, 0.7);
            // return Ok(output);
            return Err(SynthesisError::LlmError("Local LLM not configured".into()));
        }

        #[cfg(feature = "llm-remote")]
        {
            // Use API-based LLM
            let rt = tokio::runtime::Runtime::new()
                .map_err(|e| SynthesisError::LlmError(format!("Tokio error: {}", e)))?;
            rt.block_on(async {
                let client = reqwest::Client::new();
                let resp = client
                    .post("http://localhost:11434/api/generate")
                    .json(&serde_json::json!({
                        "model": "codellama:13b",
                        "prompt": prompt,
                        "stream": false,
                        "temperature": 0.7,
                        "max_tokens": 2048,
                    }))
                    .send()
                    .await
                    .map_err(|e| SynthesisError::LlmError(format!("HTTP error: {}", e)))?;

                let json: serde_json::Value = resp.json().await
                    .map_err(|e| SynthesisError::LlmError(format!("JSON error: {}", e)))?;

                Ok(json["response"].as_str().unwrap_or("").to_string())
            })
        }

        #[cfg(not(any(feature = "llm-local", feature = "llm-remote")))]
        {
            Err(SynthesisError::LlmError("No LLM backend enabled".into()))
        }
    }

    fn parse_llm_output(&self, output: &str, spec: &FunctionSpec) -> Result<Vec<CandidateImplementation>, SynthesisError> {
        // Extract code block from LLM output
        let code = if let Some(start) = output.find("<code>") {
            let start = start + 6;
            let end = output.rfind("</code>").unwrap_or(output.len());
            &output[start..end]
        } else if let Some(start) = output.find("```") {
            let start = start + 3;
            let rest = &output[start..];
            let end = rest.find("```").unwrap_or(rest.len());
            &rest[..end]
        } else {
            output
        };

        // Parse Rust code into IR
        parse_rust_into_ir(code, spec)
    }
}

// ── Public API ─────────────────────────────────────────────

/// Main entry point: synthesize implementations for a spec
pub fn synthesize(spec: &FunctionSpec, opt_level: u8) -> Result<Vec<CandidateImplementation>, SynthesisError> {
    let config = SynthesisConfig::from_opt_level(opt_level);
    let mut engine = SynthesisEngine::new(config);
    engine.run(spec)
}

// ── Error Types ───────────────────────────────────────────

#[derive(Debug)]
pub enum SynthesisError {
    NoImplementationFound,
    VerificationFailed(String),
    LlmError(String),
    TimeoutElapsed,
    InvalidSpec(String),
    InternalError(String),
}

impl std::fmt::Display for SynthesisError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SynthesisError::NoImplementationFound => write!(f, "No implementation satisfies all constraints"),
            SynthesisError::VerificationFailed(msg) => write!(f, "Verification failed: {}", msg),
            SynthesisError::LlmError(msg) => write!(f, "LLM error: {}", msg),
            SynthesisError::TimeoutElapsed => write!(f, "Synthesis timeout elapsed"),
            SynthesisError::InvalidSpec(msg) => write!(f, "Invalid specification: {}", msg),
            SynthesisError::InternalError(msg) => write!(f, "Internal error: {}", msg),
        }
    }
}

impl std::error::Error for SynthesisError {}

// ── Helper Functions ──────────────────────────────────────

fn empty_scores() -> ScoreBreakdown {
    ScoreBreakdown {
        test_pass_ratio: 0.0,
        constraint_score: 0.0,
        complexity_score: 1.0,
        quality_score: 1.0,
        synthesis_time_us: 0,
    }
}

fn composite_score(scores: &ScoreBreakdown) -> f64 {
    0.4 * scores.test_pass_ratio
        + 0.3 * scores.constraint_score
        + 0.2 * scores.complexity_score
        + 0.1 * scores.quality_score
}

fn count_holes(node: &IRNode) -> usize {
    match node {
        IRNode::Hole { .. } => 1,
        IRNode::Block(stmts) => stmts.iter().map(count_holes).sum(),
        IRNode::Let { value, body, .. } => count_holes(value) + count_holes(body),
        IRNode::If { condition, then_branch, else_branch } =>
            count_holes(condition) + count_holes(then_branch) + count_holes(else_branch),
        IRNode::While { condition, body, .. } => count_holes(condition) + count_holes(body),
        IRNode::For { start, end, body, .. } => count_holes(start) + count_holes(end) + count_holes(body),
        IRNode::Match { scrutinee, cases } =>
            count_holes(scrutinee) + cases.iter().map(|(_, b)| count_holes(b)).sum::<usize>(),
        IRNode::Call { args, .. } => args.iter().map(count_holes).sum(),
        IRNode::Return(expr) => count_holes(expr),
        IRNode::BinOp(_, l, r) => count_holes(l) + count_holes(r),
        IRNode::UnaryOp(_, inner) => count_holes(inner),
        IRNode::Lambda { body, .. } | IRNode::Closure { body, .. } => count_holes(body),
        IRNode::Collection { elements, .. } => elements.iter().map(count_holes).sum(),
        IRNode::Map { function, over } | IRNode::Filter { predicate: function, over } =>
            count_holes(function) + count_holes(over),
        IRNode::Fold { operation, initial, over } =>
            count_holes(operation) + count_holes(initial) + count_holes(over),
        IRNode::Sort { comparator, collection } => count_holes(comparator) + count_holes(collection),
        IRNode::Alloc { initial, .. } => count_holes(initial),
        IRNode::Assign { target, value } => count_holes(target) + count_holes(value),
        IRNode::Typed { node, .. } => count_holes(node),
        _ => 0, // Literals, Vars, etc.
    }
}

fn find_hole_positions(node: &IRNode) -> Vec<HoleRef> {
    let mut holes = Vec::new();
    find_holes_rec(node, &mut Vec::new(), &mut holes);
    holes
}

type HolePath = Vec<PathElem>;

#[derive(Debug, Clone)]
enum PathElem {
    Block(usize),
    LetValue,
    LetBody,
    IfCond,
    IfThen,
    IfElse,
    WhileCond,
    WhileBody,
    ForStart,
    ForEnd,
    ForBody,
    MatchScrutinee,
    MatchCase(usize),
    CallArg(usize),
    Return,
    BinOpL,
    BinOpR,
    UnaryInner,
    LambdaBody,
    CollectionElem(usize),
    MapFunc,
    MapOver,
    FilterPred,
    FilterOver,
    FoldOp,
    FoldInit,
    FoldOver,
    SortComp,
    SortColl,
    AllocInit,
    AssignTarget,
    AssignValue,
    TypedNode,
}

#[derive(Debug, Clone)]
struct HoleRef {
    path: HolePath,
}

fn find_holes_rec(node: &IRNode, path: &mut HolePath, holes: &mut Vec<HoleRef>) {
    match node {
        IRNode::Hole { .. } => {
            holes.push(HoleRef { path: path.clone() });
        }
        IRNode::Block(stmts) => {
            for (i, stmt) in stmts.iter().enumerate() {
                path.push(PathElem::Block(i));
                find_holes_rec(stmt, path, holes);
                path.pop();
            }
        }
        IRNode::Let { value, body, .. } => {
            path.push(PathElem::LetValue);
            find_holes_rec(value, path, holes);
            path.pop();
            path.push(PathElem::LetBody);
            find_holes_rec(body, path, holes);
            path.pop();
        }
        IRNode::If { condition, then_branch, else_branch } => {
            path.push(PathElem::IfCond);
            find_holes_rec(condition, path, holes);
            path.pop();
            path.push(PathElem::IfThen);
            find_holes_rec(then_branch, path, holes);
            path.pop();
            path.push(PathElem::IfElse);
            find_holes_rec(else_branch, path, holes);
            path.pop();
        }
        IRNode::While { condition, body, .. } => {
            path.push(PathElem::WhileCond);
            find_holes_rec(condition, path, holes);
            path.pop();
            path.push(PathElem::WhileBody);
            find_holes_rec(body, path, holes);
            path.pop();
        }
        IRNode::For { start, end, body, .. } => {
            path.push(PathElem::ForStart);
            find_holes_rec(start, path, holes);
            path.pop();
            path.push(PathElem::ForEnd);
            find_holes_rec(end, path, holes);
            path.pop();
            path.push(PathElem::ForBody);
            find_holes_rec(body, path, holes);
            path.pop();
        }
        IRNode::Match { scrutinee, cases } => {
            path.push(PathElem::MatchScrutinee);
            find_holes_rec(scrutinee, path, holes);
            path.pop();
            for (i, (_, body)) in cases.iter().enumerate() {
                path.push(PathElem::MatchCase(i));
                find_holes_rec(body, path, holes);
                path.pop();
            }
        }
        IRNode::Call { args, .. } => {
            for (i, arg) in args.iter().enumerate() {
                path.push(PathElem::CallArg(i));
                find_holes_rec(arg, path, holes);
                path.pop();
            }
        }
        IRNode::Return(expr) => {
            path.push(PathElem::Return);
            find_holes_rec(expr, path, holes);
            path.pop();
        }
        IRNode::BinOp(_, l, r) => {
            path.push(PathElem::BinOpL);
            find_holes_rec(l, path, holes);
            path.pop();
            path.push(PathElem::BinOpR);
            find_holes_rec(r, path, holes);
            path.pop();
        }
        IRNode::UnaryOp(_, inner) => {
            path.push(PathElem::UnaryInner);
            find_holes_rec(inner, path, holes);
            path.pop();
        }
        IRNode::Collection { elements, .. } => {
            for (i, e) in elements.iter().enumerate() {
                path.push(PathElem::CollectionElem(i));
                find_holes_rec(e, path, holes);
                path.pop();
            }
        }
        IRNode::Map { function, over } => {
            path.push(PathElem::MapFunc);
            find_holes_rec(function, path, holes);
            path.pop();
            path.push(PathElem::MapOver);
            find_holes_rec(over, path, holes);
            path.pop();
        }
        IRNode::Filter { predicate, over } => {
            path.push(PathElem::FilterPred);
            find_holes_rec(predicate, path, holes);
            path.pop();
            path.push(PathElem::FilterOver);
            find_holes_rec(over, path, holes);
            path.pop();
        }
        IRNode::Fold { operation, initial, over } => {
            path.push(PathElem::FoldOp);
            find_holes_rec(operation, path, holes);
            path.pop();
            path.push(PathElem::FoldInit);
            find_holes_rec(initial, path, holes);
            path.pop();
            path.push(PathElem::FoldOver);
            find_holes_rec(over, path, holes);
            path.pop();
        }
        IRNode::Sort { comparator, collection } => {
            path.push(PathElem::SortComp);
            find_holes_rec(comparator, path, holes);
            path.pop();
            path.push(PathElem::SortColl);
            find_holes_rec(collection, path, holes);
            path.pop();
        }
        IRNode::Lambda { body, .. } => {
            path.push(PathElem::LambdaBody);
            find_holes_rec(body, path, holes);
            path.pop();
        }
        IRNode::Alloc { initial, .. } => {
            path.push(PathElem::AllocInit);
            find_holes_rec(initial, path, holes);
            path.pop();
        }
        IRNode::Assign { target, value } => {
            path.push(PathElem::AssignTarget);
            find_holes_rec(target, path, holes);
            path.pop();
            path.push(PathElem::AssignValue);
            find_holes_rec(value, path, holes);
            path.pop();
        }
        IRNode::Typed { node, .. } => {
            path.push(PathElem::TypedNode);
            find_holes_rec(node, path, holes);
            path.pop();
        }
        _ => {} // Literals, vars — no children
    }
}

fn replace_hole(node: &mut IRNode, hole: &HoleRef, replacement: &IRNode) {
    replace_at_path(node, &hole.path, 0, replacement);
}

fn replace_at_path(node: &mut IRNode, path: &[PathElem], depth: usize, replacement: &IRNode) {
    if depth >= path.len() {
        *node = replacement.clone();
        return;
    }
    match &path[depth] {
        PathElem::Block(i) => {
            if let IRNode::Block(stmts) = node {
                replace_at_path(&mut stmts[*i], path, depth + 1, replacement);
            }
        }
        // ... (similar match arms for all PathElem variants)
        _ => {}
    }
}

fn replace_subtree(root: &mut IRNode, target: &IRNode, replacement: &IRNode) {
    if std::ptr::eq(root, target) {
        *root = replacement.clone();
        return;
    }
    // Recursive search-and-replace (simplified — real version walks the tree)
    // Uses structural equality as approximation
    if ir_equivalent(root, target) {
        *root = replacement.clone();
    }
}

fn type_compatible(a: &IRNode, b: &IRNode) -> bool {
    // Simplified: any two nodes are compatible for crossover
    true
}

fn random_subtree(node: &IRNode) -> IRNode {
    // Simplified: return a copy of a random subtree
    node.clone()
}

fn ir_equivalent(a: &IRNode, b: &IRNode) -> bool {
    // Simplified structural equivalence
    std::mem::discriminant(a) == std::mem::discriminant(b)
}

fn has_list_type(spec: &FunctionSpec) -> bool {
    let is_list = |t: &TypeRef| matches!(t, TypeRef::List(_));
    spec.params.iter().any(|p| is_list(&p.ty))
        || is_list(&spec.return_type)
}

fn build_input_ref(params: &[Param]) -> IRNode {
    if params.len() == 1 {
        IRNode::Var(params[0].name.clone())
    } else {
        let fields: Vec<IRNode> = params.iter()
            .map(|p| IRNode::Var(p.name.clone()))
            .collect();
        IRNode::Collection {
            kind: CollectionKind::Tuple,
            elements: fields,
        }
    }
}

// ── Template builders ─────────────────────────────────────

fn build_divide_and_conquer(_spec: &FunctionSpec, engine: &SynthesisEngine) -> IRNode {
    IRNode::Hole { id: engine.new_id(), expected_type: None }
}

fn build_iterator_chain(_spec: &FunctionSpec, engine: &SynthesisEngine) -> IRNode {
    IRNode::Hole { id: engine.new_id(), expected_type: None }
}

fn build_simple_loop(_spec: &FunctionSpec, engine: &SynthesisEngine) -> IRNode {
    IRNode::Hole { id: engine.new_id(), expected_type: None }
}

// ── Mutation helpers ──────────────────────────────────────

fn generate_hole_fillings(hole: &HoleRef, node: &MCTSNode) -> Vec<IRNode> {
    // Generate diverse fillings for the hole
    // In production: use LLM, type-directed search, library functions
    vec![
        IRNode::Literal(IRLiteral::Int(0)),
        IRNode::Literal(IRLiteral::Bool(true)),
        IRNode::Var("x".into()),
        IRNode::BinOp(IRBinOp::Add,
            Box::new(IRNode::Var("a".into())),
            Box::new(IRNode::Var("b".into()))),
    ]
}

fn random_filling(_hole: &HoleRef) -> IRNode {
    use rand::Rng;
    match rand::thread_rng().gen_range(0u32..5) {
        0 => IRNode::Literal(IRLiteral::Int(0)),
        1 => IRNode::Literal(IRLiteral::Bool(true)),
        2 => IRNode::Var("result".into()),
        3 => IRNode::Return(Box::new(IRNode::Var("output".into()))),
        _ => IRNode::Hole { id: 0, expected_type: None },
    }
}

fn random_ir_tree(_spec: &FunctionSpec, depth: u32, engine: &SynthesisEngine) -> IRNode {
    if depth == 0 {
        return IRNode::Hole { id: engine.new_id(), expected_type: None };
    }
    use rand::Rng;
    match rand::thread_rng().gen_range(0u32..8) {
        0 => IRNode::Block(vec![
            random_ir_tree(_spec, depth - 1, engine),
            IRNode::Return(Box::new(
                IRNode::Var("result".into())
            )),
        ]),
        1 => IRNode::If {
            condition: Box::new(random_ir_tree(_spec, depth - 1, engine)),
            then_branch: Box::new(random_ir_tree(_spec, depth - 1, engine)),
            else_branch: Box::new(random_ir_tree(_spec, depth - 1, engine)),
        },
        2 => IRNode::For {
            var: "i".into(),
            start: Box::new(IRNode::Literal(IRLiteral::Int(0))),
            end: Box::new(IRNode::Literal(IRLiteral::Int(10))),
            body: Box::new(random_ir_tree(_spec, depth - 1, engine)),
        },
        3 => IRNode::Call { function: "_".into(), args: vec![] },
        4 => IRNode::Return(Box::new(random_ir_tree(_spec, depth - 1, engine))),
        5 => IRNode::Collection { kind: CollectionKind::List, elements: vec![] },
        _ => IRNode::Hole { id: engine.new_id(), expected_type: None },
    }
}

fn parse_rust_into_ir(code: &str, _spec: &FunctionSpec) -> Result<Vec<CandidateImplementation>, SynthesisError> {
    // Simplified: wrap raw code in an opaque IR node
    // In production: use a proper Rust parser (syn) to build IR
    Ok(vec![CandidateImplementation {
        id: 0,
        body: IRNode::Typed {
            node: Box::new(IRNode::Block(vec![])),
            ty: TypeRef::Named("RawRust".into()),
        },
        spec_name: "".into(),
        spec: _spec.clone(),
        score: 0.0,
        scores: empty_scores(),
        generation: 0,
        provenance: Provenance::LLMGenerated {
            model: "codellama:13b".into(),
            prompt_hash: 0,
        },
        verified: false,
    }])
}

fn epr_to_pattern(expr: &Expr) -> IRPattern {
    match expr {
        Expr::IntLit(n) => IRPattern::Literal(IRLiteral::Int(*n)),
        Expr::StringLit(s) => IRPattern::Literal(IRLiteral::String(s.clone())),
        Expr::BoolLit(b) => IRPattern::Literal(IRLiteral::Bool(*b)),
        Expr::Call(name, args) => {
            let sub_patterns: Vec<IRPattern> = args.iter().map(expr_to_pattern).collect();
            IRPattern::Constructor(name.clone(), sub_patterns)
        }
        Expr::Var(v) => IRPattern::Variable(v.clone()),
        _ => IRPattern::Wildcard,
    }
}

fn expr_to_ir(expr: &Expr) -> IRNode {
    match expr {
        Expr::IntLit(n) => IRNode::Literal(IRLiteral::Int(*n)),
        Expr::FloatLit(f) => IRNode::Literal(IRLiteral::Float(*f)),
        Expr::BoolLit(b) => IRNode::Literal(IRLiteral::Bool(*b)),
        Expr::StringLit(s) => IRNode::Literal(IRLiteral::String(s.clone())),
        Expr::Var(v) => IRNode::Var(v.clone()),
        Expr::Call(name, args) => IRNode::Call {
            function: name.clone(),
            args: args.iter().map(expr_to_ir).collect(),
        },
        Expr::BinOp(op, l, r) => IRNode::BinOp(
            binop_to_ir(*op),
            Box::new(expr_to_ir(l)),
            Box::new(expr_to_ir(r)),
        ),
        Expr::UnaryOp(op, inner) => IRNode::UnaryOp(
            unaryop_to_ir(*op),
            Box::new(expr_to_ir(inner)),
        ),
        _ => IRNode::Hole { id: 0, expected_type: None },
    }
}

fn binop_to_ir(op: BinOp) -> IRBinOp {
    match op {
        BinOp::Add => IRBinOp::Add,
        BinOp::Sub => IRBinOp::Sub,
        BinOp::Mul => IRBinOp::Mul,
        BinOp::Div => IRBinOp::Div,
        BinOp::Mod => IRBinOp::Mod,
        BinOp::And => IRBinOp::And,
        BinOp::Or => IRBinOp::Or,
        BinOp::Eq => IRBinOp::Eq,
        BinOp::Neq => IRBinOp::Neq,
        BinOp::Lt => IRBinOp::Lt,
        BinOp::Le => IRBinOp::Le,
        BinOp::Gt => IRBinOp::Gt,
        BinOp::Ge => IRBinOp::Ge,
        BinOp::Concat => IRBinOp::Concat,
    }
}

fn unaryop_to_ir(op: UnaryOp) -> IRUnaryOp {
    match op {
        UnaryOp::Neg => IRUnaryOp::Neg,
        UnaryOp::Not => IRUnaryOp::Not,
    }
}

fn evaluate_candidate(candidate: &CandidateImplementation, spec: &FunctionSpec) -> ScoreBreakdown {
    // Test pass ratio
    let test_score = if spec.tests.is_empty() {
        0.5 // No tests: neutral score
    } else {
        let passed = spec.tests.iter().filter(|_test| {
            // Execute test logic (simplified)
            true
        }).count();
        passed as f64 / spec.tests.len() as f64
    };

    // Constraint score: structural similarity to constraint shape
    let constraint_score = 0.7; // Placeholder — real version checks Z3

    // Complexity: check if body matches Big-O bound
    let complexity_score = estimate_complexity(&candidate.body, spec);

    // Quality: AST size/readability heuristic
    let quality_score = estimate_quality(&candidate.body);

    ScoreBreakdown {
        test_pass_ratio: test_score,
        constraint_score,
        complexity_score,
        quality_score,
        synthesis_time_us: 0,
    }
}

fn estimate_complexity(body: &IRNode, spec: &FunctionSpec) -> f64 {
    let depth = ast_depth(body);
    let has_nested_loops = count_loops(body) > 1;
    let has_recursion = has_recursive_calls(body);

    if let Some(ref bound) = spec.complexity {
        match bound.bound {
            BigO::Constant => if depth < 2 { 1.0 } else { 0.3 },
            BigO::Linear => if depth < 6 && !has_nested_loops { 1.0 } else { 0.4 },
            BigO::Linearithmic => if !has_recursion || depth < 12 { 1.0 } else { 0.5 },
            BigO::Quadratic => if has_nested_loops { 1.0 } else { 0.6 },
            _ => 0.7, // Unknown — neutral score
        }
    } else {
        0.8 // No bound specified
    }
}

fn ast_depth(node: &IRNode) -> usize {
    match node {
        IRNode::Hole { .. } | IRNode::Literal(_) | IRNode::Var(_) => 1,
        IRNode::Block(stmts) => 1 + stmts.iter().map(ast_depth).max().unwrap_or(0),
        IRNode::Let { value, body, .. } => 1 + ast_depth(value).max(ast_depth(body)),
        IRNode::If { condition, then_branch, else_branch } =>
            1 + ast_depth(condition).max(ast_depth(then_branch).max(ast_depth(else_branch))),
        IRNode::While { condition, body, .. } => 1 + ast_depth(condition).max(ast_depth(body)),
        IRNode::For { start, end, body, .. } =>
            1 + ast_depth(start).max(ast_depth(end)).max(ast_depth(body)),
        IRNode::Match { scrutinee, cases } =>
            1 + ast_depth(scrutinee).max(cases.iter().map(|(_, b)| ast_depth(b)).max().unwrap_or(0)),
        IRNode::Call { args, .. } => 1 + args.iter().map(ast_depth).max().unwrap_or(0),
        IRNode::Return(expr) => 1 + ast_depth(expr),
        IRNode::BinOp(_, l, r) => 1 + ast_depth(l).max(ast_depth(r)),
        IRNode::UnaryOp(_, inner) => 1 + ast_depth(inner),
        IRNode::Lambda { body, .. } | IRNode::Closure { body, .. } => 1 + ast_depth(body),
        IRNode::Collection { elements, .. } => 1 + elements.iter().map(ast_depth).max().unwrap_or(0),
        IRNode::Map { function, over } => 1 + ast_depth(function).max(ast_depth(over)),
        IRNode::Filter { predicate, over } => 1 + ast_depth(predicate).max(ast_depth(over)),
        IRNode::Fold { operation, initial, over } =>
            1 + ast_depth(operation).max(ast_depth(initial)).max(ast_depth(over)),
        IRNode::Sort { comparator, collection } => 1 + ast_depth(comparator).max(ast_depth(collection)),
        IRNode::Alloc { initial, .. } => 1 + ast_depth(initial),
        IRNode::Assign { target, value } => 1 + ast_depth(target).max(ast_depth(value)),
        IRNode::Typed { node, .. } => 1 + ast_depth(node),
    }
}

fn count_loops(body: &IRNode) -> usize {
    match body {
        IRNode::While { body: b, .. } | IRNode::For { body: b, .. } =>
            1 + count_loops(b),
        IRNode::Block(stmts) => stmts.iter().map(count_loops).sum(),
        IRNode::If { then_branch, else_branch, .. } =>
            count_loops(then_branch) + count_loops(else_branch),
        IRNode::Let { value, body, .. } => count_loops(value) + count_loops(body),
        IRNode::Match { cases, .. } => cases.iter().map(|(_, b)| count_loops(b)).sum(),
        _ => 0,
    }
}

fn has_recursive_calls(body: &IRNode) -> bool {
    match body {
        IRNode::Call { function, .. } => function == "self",
        IRNode::Block(stmts) => stmts.iter().any(has_recursive_calls),
        IRNode::If { then_branch, else_branch, .. } =>
            has_recursive_calls(then_branch) || has_recursive_calls(else_branch),
        IRNode::Match { cases, .. } => cases.iter().any(|(_, b)| has_recursive_calls(b)),
        _ => false,
    }
}

fn estimate_quality(body: &IRNode) -> f64 {
    // Heuristic: smaller, well-structured AST = higher quality
    let size = ast_node_count(body);
    let depth = ast_depth(body);

    if size < 3 { return 0.3; } // Too small
    if depth > 20 { return 0.3; } // Too deep
    if size > 500 { return 0.4; } // Too large
    0.7 // Default decent score
}

fn ast_node_count(node: &IRNode) -> usize {
    match node {
        IRNode::Hole { .. } | IRNode::Literal(_) | IRNode::Var(_) => 1,
        IRNode::Block(stmts) => 1 + stmts.iter().map(ast_node_count).sum::<usize>(),
        IRNode::Let { value, body, .. } => 1 + ast_node_count(value) + ast_node_count(body),
        IRNode::If { condition, then_branch, else_branch } =>
            1 + ast_node_count(condition) + ast_node_count(then_branch) + ast_node_count(else_branch),
        IRNode::While { condition, body, .. } =>
            1 + ast_node_count(condition) + ast_node_count(body),
        IRNode::For { start, end, body, .. } =>
            1 + ast_node_count(start) + ast_node_count(end) + ast_node_count(body),
        IRNode::Match { scrutinee, cases } =>
            1 + ast_node_count(scrutinee)
                + cases.iter().map(|(_, b)| ast_node_count(b)).sum::<usize>(),
        IRNode::Call { args, .. } => 1 + args.iter().map(ast_node_count).sum::<usize>(),
        IRNode::Return(expr) => 1 + ast_node_count(expr),
        IRNode::BinOp(_, l, r) => 1 + ast_node_count(l) + ast_node_count(r),
        IRNode::UnaryOp(_, inner) => 1 + ast_node_count(inner),
        IRNode::Lambda { body, .. } | IRNode::Closure { body, .. } => 1 + ast_node_count(body),
        IRNode::Collection { elements, .. } => 1 + elements.iter().map(ast_node_count).sum::<usize>(),
        IRNode::Map { function, over } => 1 + ast_node_count(function) + ast_node_count(over),
        IRNode::Filter { predicate, over } => 1 + ast_node_count(predicate) + ast_node_count(over),
        IRNode::Fold { operation, initial, over } =>
            1 + ast_node_count(operation) + ast_node_count(initial) + ast_node_count(over),
        IRNode::Sort { comparator, collection } =>
            1 + ast_node_count(comparator) + ast_node_count(collection),
        IRNode::Alloc { initial, .. } => 1 + ast_node_count(initial),
        IRNode::Assign { target, value } => 1 + ast_node_count(target) + ast_node_count(value),
        IRNode::Typed { node, .. } => 1 + ast_node_count(node),
    }
}

fn tournament_select<'a>(
    population: &'a [CandidateImplementation],
    tournament_size: usize,
    rng: &mut impl Rng,
) -> &'a CandidateImplementation {
    let mut best = &population[rng.gen_range(0..population.len())];
    for _ in 1..tournament_size {
        let challenger = &population[rng.gen_range(0..population.len())];
        if challenger.score > best.score {
            best = challenger;
        }
    }
    best
}

// ── Stub helpers ──────────────────────────────────────────

fn inline_random_call(_body: &mut IRNode) {}
fn swap_equivalent(_body: &mut IRNode) {}
fn optimize_loop(_body: &mut IRNode) {}
fn add_parallel_hint(_body: &mut IRNode) {}
fn random_rewrite(_body: &mut IRNode) {}

fn format_params(params: &[Param]) -> String {
    params.iter()
        .map(|p| format!("{}: {}", p.name, p.ty))
        .collect::<Vec<_>>()
        .join(", ")
}

fn format_constraints(constraints: &[Constraint]) -> String {
    if constraints.is_empty() {
        return "none".into();
    }
    constraints.iter()
        .map(|c| format!("- {}", format_constraint(c)))
        .collect::<Vec<_>>()
        .join("\n")
}

fn format_constraint(c: &Constraint) -> String {
    match c {
        Constraint::True => "true".into(),
        Constraint::Expr(e) => format!("{:?}", e),
        Constraint::Eq(a, b) => format!("{:?} == {:?}", a, b),
        Constraint::Order(op, a, b) => format!("{:?} {:?} {:?}", a, op, b),
        Constraint::And(parts) => parts.iter().map(format_constraint).collect::<Vec<_>>().join(" && "),
        Constraint::Implies(a, b) => format!("({} => {})", format_constraint(a), format_constraint(b)),
        Constraint::Not(inner) => format!("!({})", format_constraint(inner)),
        _ => format!("{:?}", c),
    }
}

fn format_tests(tests: &[Test]) -> String {
    tests.iter()
        .map(|t| format!("  {} → {}", format_expr(&t.input), format_expr(&t.expected_output)))
        .collect::<Vec<_>>()
        .join("\n")
}

fn format_expr(expr: &Expr) -> String {
    match expr {
        Expr::IntLit(n) => n.to_string(),
        Expr::StringLit(s) => format!("\"{}\"", s),
        Expr::Var(v) => v.clone(),
        Expr::Call(name, args) => {
            let args: Vec<String> = args.iter().map(format_expr).collect();
            format!("{}({})", name, args.join(", "))
        }
        _ => format!("{:?}", expr),
    }
}

impl ComplexityBound {
    fn dimension_name(&self) -> &str {
        match self.dimension {
            ComplexityDimension::Time => "time",
            ComplexityDimension::Space => "space",
            ComplexityDimension::AmortizedTime => "amortized time",
            ComplexityDimension::Communication => "communication",
        }
    }
}
